/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lea.output.gui;

import com.lea.bll.datamanagers.DdlDataManager;
import com.lea.utilities.OptionKeyValue;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lea
 */
public class Testing_FrameOkv extends javax.swing.JFrame {

    /**
     * Creates new form Testing_FrameOkv
     */
    public Testing_FrameOkv() {
        initComponents();
        ddlManager = new DdlDataManager();
        loadCountries();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDrzava = new javax.swing.JComboBox();
        cbGrad = new javax.swing.JComboBox();
        btnIspis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbDrzava.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDrzavaActionPerformed(evt);
            }
        });

        cbGrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIspis.setText("Prikaži");
        btnIspis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIspisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIspis)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbDrzava, 0, 177, Short.MAX_VALUE)
                        .addComponent(cbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(cbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnIspis)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIspisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIspisActionPerformed
        // TODO add your handling code here:
        int selectedCityIndex = ((OptionKeyValue) cbGrad.getSelectedItem()).getKey();
        String selectedCityName = ((OptionKeyValue) cbGrad.getSelectedItem()).getValue();
        JOptionPane.showMessageDialog(null, "Id odabranog grada je: " + selectedCityIndex + "\nIme grada je: " + selectedCityName);
    }//GEN-LAST:event_btnIspisActionPerformed

    private void cbDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDrzavaActionPerformed
        // TODO add your handling code here:
        int countryId = ((OptionKeyValue) cbDrzava.getSelectedItem()).getKey();
        loadCities(countryId);
    }//GEN-LAST:event_cbDrzavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testing_FrameOkv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testing_FrameOkv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testing_FrameOkv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testing_FrameOkv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testing_FrameOkv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIspis;
    private javax.swing.JComboBox cbDrzava;
    private javax.swing.JComboBox cbGrad;
    // End of variables declaration//GEN-END:variables

    private DefaultComboBoxModel<OptionKeyValue> comboModelCities;
    private DefaultComboBoxModel<OptionKeyValue> comboModelCountries;
    private DdlDataManager ddlManager;

    private void loadCountries() {
        comboModelCountries = new DefaultComboBoxModel<>();
        
//        List<OptionKeyValue> citiesList = ddlManager.getAllCities();
//        List<OptionKeyValue> countriesList = ddlManager.getAllCountries();
        //ddlManager.getAllCitiesByCountry(3).forEach(c -> comboModelCities.addElement(c));
        ddlManager.getAllCountries().forEach(c -> comboModelCountries.addElement(c));

        //cbGrad.setModel(comboModelCities);
        cbDrzava.setModel(comboModelCountries);
        if (comboModelCountries.getSize() != 0) {
            cbDrzava.setSelectedIndex(0);
        }
    }

    private void loadCities(int countryId) {
        comboModelCities = new DefaultComboBoxModel<>();
        ddlManager = new DdlDataManager();
        ddlManager.getAllCitiesByCountry(countryId).forEach(c -> comboModelCities.addElement(c));
        cbGrad.setModel(comboModelCities);
    }

}
