package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="Address"
    ,schema="dbo"
    ,catalog="OutpatientManagement"
)
public class Address  implements java.io.Serializable {


     private int idaddress;
     private City city;
     private String fullStreet;
     private String pincode;
     private Set<BasicDetails> basicDetailses = new HashSet<BasicDetails>(0);

    public Address() {
    }

	
    public Address(int idaddress, City city, String fullStreet, String pincode) {
        this.idaddress = idaddress;
        this.city = city;
        this.fullStreet = fullStreet;
        this.pincode = pincode;
    }
    public Address(int idaddress, City city, String fullStreet, String pincode, Set<BasicDetails> basicDetailses) {
       this.idaddress = idaddress;
       this.city = city;
       this.fullStreet = fullStreet;
       this.pincode = pincode;
       this.basicDetailses = basicDetailses;
    }
   
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDAddress", unique=true, nullable=false)
    public int getIdaddress() {
        return this.idaddress;
    }
    
    public void setIdaddress(int idaddress) {
        this.idaddress = idaddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CityID", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="FullStreet", nullable=false)
    public String getFullStreet() {
        return this.fullStreet;
    }
    
    public void setFullStreet(String fullStreet) {
        this.fullStreet = fullStreet;
    }

    
    @Column(name="PINcode", nullable=false)
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set<BasicDetails> getBasicDetailses() {
        return this.basicDetailses;
    }
    
    public void setBasicDetailses(Set<BasicDetails> basicDetailses) {
        this.basicDetailses = basicDetailses;
    }




}


