package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppointmentService generated by hbm2java
 */
@Entity
@Table(name="AppointmentService"
    ,schema="dbo"
    ,catalog="VirgoHospitals"
)
public class AppointmentService implements EntityBase, java.io.Serializable {

     private int idappointmentService;
     private Appointment appointment;
     private HospitalService hospitalService;

    public AppointmentService() {
    }

	
    public AppointmentService(int idappointmentService) {
        this.idappointmentService = idappointmentService;
    }
    public AppointmentService(int idappointmentService, Appointment appointment, HospitalService hospitalService) {
       this.idappointmentService = idappointmentService;
       this.appointment = appointment;
       this.hospitalService = hospitalService;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDAppointmentService", unique=true, nullable=false)
    public int getIdappointmentService() {
        return this.idappointmentService;
    }
    
    public void setIdappointmentService(int idappointmentService) {
        this.idappointmentService = idappointmentService;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AppointmentID")
    public Appointment getAppointment() {
        return this.appointment;
    }
    
    public void setAppointment(Appointment appointment) {
        this.appointment = appointment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="HospitalServiceID")
    public HospitalService getHospitalService() {
        return this.hospitalService;
    }
    
    public void setHospitalService(HospitalService hospitalService) {
        this.hospitalService = hospitalService;
    }

    @Override
    public int fetchEntityId() {
        return getIdappointmentService();
    }

}


