package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComplaintDetails generated by hbm2java
 */
@Entity
@Table(name="ComplaintDetails"
    ,schema="dbo"
    ,catalog="VirgoHospitals"
)
public class ComplaintDetails  implements java.io.Serializable {


     private int idcomplaintDetails;
     private String complaint;
     private String treatmentHistory;
     private String treatedAtHospital;
     private Set<Patient> patients = new HashSet<Patient>(0);

    public ComplaintDetails() {
    }

	
    public ComplaintDetails(int idcomplaintDetails) {
        this.idcomplaintDetails = idcomplaintDetails;
    }
    public ComplaintDetails(int idcomplaintDetails, String complaint, String treatmentHistory, String treatedAtHospital, Set<Patient> patients) {
       this.idcomplaintDetails = idcomplaintDetails;
       this.complaint = complaint;
       this.treatmentHistory = treatmentHistory;
       this.treatedAtHospital = treatedAtHospital;
       this.patients = patients;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDComplaintDetails", unique=true, nullable=false)
    public int getIdcomplaintDetails() {
        return this.idcomplaintDetails;
    }
    
    public void setIdcomplaintDetails(int idcomplaintDetails) {
        this.idcomplaintDetails = idcomplaintDetails;
    }

    
    @Column(name="Complaint")
    public String getComplaint() {
        return this.complaint;
    }
    
    public void setComplaint(String complaint) {
        this.complaint = complaint;
    }

    
    @Column(name="TreatmentHistory")
    public String getTreatmentHistory() {
        return this.treatmentHistory;
    }
    
    public void setTreatmentHistory(String treatmentHistory) {
        this.treatmentHistory = treatmentHistory;
    }

    
    @Column(name="TreatedAtHospital")
    public String getTreatedAtHospital() {
        return this.treatedAtHospital;
    }
    
    public void setTreatedAtHospital(String treatedAtHospital) {
        this.treatedAtHospital = treatedAtHospital;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="complaintDetails")
    public Set<Patient> getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }




}


