package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContactInformation generated by hbm2java
 */
@Entity
@Table(name="ContactInformation"
    ,schema="dbo"
    ,catalog="OutpatientManagement"
)
public class ContactInformation  implements java.io.Serializable {


     private int idcontactInformation;
     private String telephone;
     private String mobilePhone;
     private String email;
     private Set<BasicDetails> basicDetailses = new HashSet<BasicDetails>(0);

    public ContactInformation() {
    }

	
    public ContactInformation(int idcontactInformation) {
        this.idcontactInformation = idcontactInformation;
    }
    public ContactInformation(int idcontactInformation, String telephone, String mobilePhone, String email, Set<BasicDetails> basicDetailses) {
       this.idcontactInformation = idcontactInformation;
       this.telephone = telephone;
       this.mobilePhone = mobilePhone;
       this.email = email;
       this.basicDetailses = basicDetailses;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDContactInformation", unique=true, nullable=false)
    public int getIdcontactInformation() {
        return this.idcontactInformation;
    }
    
    public void setIdcontactInformation(int idcontactInformation) {
        this.idcontactInformation = idcontactInformation;
    }

    
    @Column(name="Telephone")
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="MobilePhone")
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    
    @Column(name="Email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contactInformation")
    public Set<BasicDetails> getBasicDetailses() {
        return this.basicDetailses;
    }
    
    public void setBasicDetailses(Set<BasicDetails> basicDetailses) {
        this.basicDetailses = basicDetailses;
    }




}


