package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="Country"
    ,schema="dbo"
    ,catalog="VirgoHospitals"
)
public class Country  implements java.io.Serializable {


     private int idcountry;
     private String name;
     private Set<City> cities = new HashSet<City>(0);

    public Country() {
    }

	
    public Country(int idcountry, String name) {
        this.idcountry = idcountry;
        this.name = name;
    }
    public Country(int idcountry, String name, Set<City> cities) {
       this.idcountry = idcountry;
       this.name = name;
       this.cities = cities;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDCountry", unique=true, nullable=false)
    public int getIdcountry() {
        return this.idcountry;
    }
    
    public void setIdcountry(int idcountry) {
        this.idcountry = idcountry;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }




}


