package com.lea.dal.domain.entities;
// Generated 30.06.2018. 18:46:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DoctorSpecialization generated by hbm2java
 */
@Entity
@Table(name="DoctorSpecialization"
    ,schema="dbo"
    ,catalog="VirgoHospitals"
)
public class DoctorSpecialization  implements java.io.Serializable {


     private int iddoctorSpecialization;
     private String name;
     private Set<Doctor> doctors = new HashSet<Doctor>(0);

    public DoctorSpecialization() {
    }

	
    public DoctorSpecialization(int iddoctorSpecialization, String name) {
        this.iddoctorSpecialization = iddoctorSpecialization;
        this.name = name;
    }
    public DoctorSpecialization(int iddoctorSpecialization, String name, Set<Doctor> doctors) {
       this.iddoctorSpecialization = iddoctorSpecialization;
       this.name = name;
       this.doctors = doctors;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDDoctorSpecialization", unique=true, nullable=false)
    public int getIddoctorSpecialization() {
        return this.iddoctorSpecialization;
    }
    
    public void setIddoctorSpecialization(int iddoctorSpecialization) {
        this.iddoctorSpecialization = iddoctorSpecialization;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctorSpecialization")
    public Set<Doctor> getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set<Doctor> doctors) {
        this.doctors = doctors;
    }




}


