package com.lea.dal.domain.entities;
// Generated 30.06.2018. 18:46:55 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaritalStatus generated by hbm2java
 */
@Entity
@Table(name="MaritalStatus"
    ,schema="dbo"
    ,catalog="VirgoHospitals"
)
public class MaritalStatus  implements java.io.Serializable {


     private int idmaritalStatus;
     private String name;
     private Set<PersonalDetails> personalDetailses = new HashSet<PersonalDetails>(0);

    public MaritalStatus() {
    }

	
    public MaritalStatus(int idmaritalStatus) {
        this.idmaritalStatus = idmaritalStatus;
    }
    public MaritalStatus(int idmaritalStatus, String name, Set<PersonalDetails> personalDetailses) {
       this.idmaritalStatus = idmaritalStatus;
       this.name = name;
       this.personalDetailses = personalDetailses;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDMaritalStatus", unique=true, nullable=false)
    public int getIdmaritalStatus() {
        return this.idmaritalStatus;
    }
    
    public void setIdmaritalStatus(int idmaritalStatus) {
        this.idmaritalStatus = idmaritalStatus;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maritalStatus")
    public Set<PersonalDetails> getPersonalDetailses() {
        return this.personalDetailses;
    }
    
    public void setPersonalDetailses(Set<PersonalDetails> personalDetailses) {
        this.personalDetailses = personalDetailses;
    }




}


