package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicalDetails generated by hbm2java
 */
@Entity
@Table(name="MedicalDetails"
    ,schema="dbo"
    ,catalog="VirgoHospitals"
)
public class MedicalDetails extends EntityBase implements java.io.Serializable {


     private int idmedicalDetails;
     private String allergiesCondition;
     private String diabeticCondition;
     private String hypertensiveCondition;
     private String cardiacCondition;
     private String respiratoryCondition;
     private String digestiveCondition;
     private String muscularCondition;
     private String neurologicalCondition;
     private Set<Patient> patients = new HashSet<Patient>(0);

    public MedicalDetails() {
    }

	
    public MedicalDetails(int idmedicalDetails) {
        this.idmedicalDetails = idmedicalDetails;
    }
    public MedicalDetails(int idmedicalDetails, String allergiesCondition, String diabeticCondition, String hypertensiveCondition, String cardiacCondition, String respiratoryCondition, String digestiveCondition, String muscularCondition, String neurologicalCondition, Set<Patient> patients) {
       this.idmedicalDetails = idmedicalDetails;
       this.allergiesCondition = allergiesCondition;
       this.diabeticCondition = diabeticCondition;
       this.hypertensiveCondition = hypertensiveCondition;
       this.cardiacCondition = cardiacCondition;
       this.respiratoryCondition = respiratoryCondition;
       this.digestiveCondition = digestiveCondition;
       this.muscularCondition = muscularCondition;
       this.neurologicalCondition = neurologicalCondition;
       this.patients = patients;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDMedicalDetails", unique=true, nullable=false)
    public int getIdmedicalDetails() {
        return this.idmedicalDetails;
    }
    
    public void setIdmedicalDetails(int idmedicalDetails) {
        this.idmedicalDetails = idmedicalDetails;
    }
    
    @Column(name="AllergiesCondition")
    public String getAllergiesCondition() {
        return this.allergiesCondition;
    }
    
    public void setAllergiesCondition(String allergiesCondition) {
        this.allergiesCondition = allergiesCondition;
    }

    
    @Column(name="DiabeticCondition")
    public String getDiabeticCondition() {
        return this.diabeticCondition;
    }
    
    public void setDiabeticCondition(String diabeticCondition) {
        this.diabeticCondition = diabeticCondition;
    }

    
    @Column(name="HypertensiveCondition")
    public String getHypertensiveCondition() {
        return this.hypertensiveCondition;
    }
    
    public void setHypertensiveCondition(String hypertensiveCondition) {
        this.hypertensiveCondition = hypertensiveCondition;
    }

    
    @Column(name="CardiacCondition")
    public String getCardiacCondition() {
        return this.cardiacCondition;
    }
    
    public void setCardiacCondition(String cardiacCondition) {
        this.cardiacCondition = cardiacCondition;
    }

    
    @Column(name="RespiratoryCondition")
    public String getRespiratoryCondition() {
        return this.respiratoryCondition;
    }
    
    public void setRespiratoryCondition(String respiratoryCondition) {
        this.respiratoryCondition = respiratoryCondition;
    }

    
    @Column(name="DigestiveCondition")
    public String getDigestiveCondition() {
        return this.digestiveCondition;
    }
    
    public void setDigestiveCondition(String digestiveCondition) {
        this.digestiveCondition = digestiveCondition;
    }

    
    @Column(name="MuscularCondition")
    public String getMuscularCondition() {
        return this.muscularCondition;
    }
    
    public void setMuscularCondition(String muscularCondition) {
        this.muscularCondition = muscularCondition;
    }

    
    @Column(name="NeurologicalCondition")
    public String getNeurologicalCondition() {
        return this.neurologicalCondition;
    }
    
    public void setNeurologicalCondition(String neurologicalCondition) {
        this.neurologicalCondition = neurologicalCondition;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicalDetails")
    public Set<Patient> getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }




}


