package com.lea.dal.domain.entities;
// Generated 28.06.2018. 08:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonalDetails generated by hbm2java
 */
@Entity
@Table(name="PersonalDetails"
    ,schema="dbo"
    ,catalog="OutpatientManagement"
)
public class PersonalDetails  implements java.io.Serializable {


     private int idpersonalDetails;
     private String maritalStatus;
     private String occupation;
     private Double height;
     private Double weight;
     private String bloodTypeRh;
     private Set<Patient> patients = new HashSet<Patient>(0);

    public PersonalDetails() {
    }

	
    public PersonalDetails(int idpersonalDetails) {
        this.idpersonalDetails = idpersonalDetails;
    }
    public PersonalDetails(int idpersonalDetails, String maritalStatus, String occupation, Double height, Double weight, String bloodTypeRh, Set<Patient> patients) {
       this.idpersonalDetails = idpersonalDetails;
       this.maritalStatus = maritalStatus;
       this.occupation = occupation;
       this.height = height;
       this.weight = weight;
       this.bloodTypeRh = bloodTypeRh;
       this.patients = patients;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="IDPersonalDetails", unique=true, nullable=false)
    public int getIdpersonalDetails() {
        return this.idpersonalDetails;
    }
    
    public void setIdpersonalDetails(int idpersonalDetails) {
        this.idpersonalDetails = idpersonalDetails;
    }

    
    @Column(name="MaritalStatus")
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    
    @Column(name="Occupation")
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="Height", precision=53, scale=0)
    public Double getHeight() {
        return this.height;
    }
    
    public void setHeight(Double height) {
        this.height = height;
    }

    
    @Column(name="Weight", precision=53, scale=0)
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    
    @Column(name="BloodTypeRH")
    public String getBloodTypeRh() {
        return this.bloodTypeRh;
    }
    
    public void setBloodTypeRh(String bloodTypeRh) {
        this.bloodTypeRh = bloodTypeRh;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personalDetails")
    public Set<Patient> getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }




}


