/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lea.gui.cards;

import com.lea.bll.datamanagers.ReportsManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Lea
 */
public class StatisticsCard extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsCard
     */
    
    private static final ReportsManager DATA_MANAGER = new ReportsManager();
    
    public StatisticsCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGeneralReport = new javax.swing.JButton();
        btnAppointmentsPerDoctor = new javax.swing.JButton();
        btnServicesPerPatient = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 61, 61), 1, true));
        setPreferredSize(new java.awt.Dimension(730, 400));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 112, 11));
        jLabel1.setText("STATISTCS REPORTS");

        jLabel2.setText("Generate report:");

        btnGeneralReport.setText("General Numbers");
        btnGeneralReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralReportActionPerformed(evt);
            }
        });

        btnAppointmentsPerDoctor.setText("Appointments per Doctor");
        btnAppointmentsPerDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentsPerDoctorActionPerformed(evt);
            }
        });

        btnServicesPerPatient.setText("Services sum per Patient");
        btnServicesPerPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesPerPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnServicesPerPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAppointmentsPerDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGeneralReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGeneralReport))
                .addGap(18, 18, 18)
                .addComponent(btnAppointmentsPerDoctor)
                .addGap(18, 18, 18)
                .addComponent(btnServicesPerPatient)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicesPerPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesPerPatientActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,  DATA_MANAGER.getServicesSumPerPatient());
    }//GEN-LAST:event_btnServicesPerPatientActionPerformed

    private void btnAppointmentsPerDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsPerDoctorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, DATA_MANAGER.getApppointmentsPerDoctorReport());
    }//GEN-LAST:event_btnAppointmentsPerDoctorActionPerformed

    private void btnGeneralReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralReportActionPerformed
        JOptionPane.showMessageDialog(null, DATA_MANAGER.getEntityNumbersReport());
    }//GEN-LAST:event_btnGeneralReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentsPerDoctor;
    private javax.swing.JButton btnGeneralReport;
    private javax.swing.JButton btnServicesPerPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
